# This workflow will test if running the integration tests works.
name: .NET Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t mov2gif-client -f src/Mov2Gif.Client/Dockerfile .

    - name: Run integration tests
      run: docker run --rm --entrypoint "dotnet" mov2gif-client test src/Tests/Mov2Gif.IntegrationTests --verbosity normal
