# This workflow will test if running the integration tests works.
name: .NET Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build --target build -t mov2gif-client-build -f src/Mov2Gif.Client/Dockerfile .

    - name: Run integration tests
      working-directory: /src
      run: docker run --rm mov2gif-client-build dotnet test Tests/Mov2Gif.IntegrationTests/Mov2Gif.IntegrationTests.csproj --verbosity normal
