# This workflow will test if running the integration tests works.
name: .NET Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build integration tests image
      run: docker build -t mov2gif-integration-tests -f src/Tests/Mov2Gif.IntegrationTests/Dockerfile .

    - name: Run integration tests
      run: docker run --rm mov2gif-integration-tests
